-- Give an example of an unnormalized table. Describe why it is problematic to have 
-- an unnormalized table in the database. Include some example data in your answer.
-- The data should show clearly the problem (or problems) unnormalized table causes.
