-- Northwind company has many products for sale. Find out how many orders include
-- each of the products. Write a query which returns all company's products 
-- (the name of the product) and the number of orders. Include the products which are 
-- not part of any order in the result.
